ERROR:root:Exception Occured
Traceback (most recent call last):
  File "D:\Users\hank\Documents\Code\projects\SecurityRabbitTest\src\main.py", line 30, in process_files
    file_info = analysis.file_info(file_name)
  File "D:\Users\hank\Documents\Code\projects\SecurityRabbitTest\src\analysis.py", line 90, in file_info
    pefile_infos_dict = pefile_infos(pe_file)
  File "D:\Users\hank\Documents\Code\projects\SecurityRabbitTest\src\analysis.py", line 268, in pefile_infos
    export_li.append([hex(pe_file.OPTIONAL_HEADER.ImageBase + exp.address), exp.name.decode('ascii'), exp.ordinal])
AttributeError: 'NoneType' object has no attribute 'decode'


ERROR:root:Exception Occured
Traceback (most recent call last):
  File "D:\Users\hank\Documents\Code\projects\SecurityRabbitTest\src\main.py", line 30, in process_files
    file_info = analysis.file_info(file_name)
  File "D:\Users\hank\Documents\Code\projects\SecurityRabbitTest\src\analysis.py", line 82, in file_info
    sigcheck_dict = sigcheck(filepath)
  File "D:\Users\hank\Documents\Code\projects\SecurityRabbitTest\src\analysis.py", line 105, in sigcheck
    sigcheck_str = sigcheck_output.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 2617: invalid start byte



ERROR:root:Exception Occured
Traceback (most recent call last):
  File "D:\Users\hank\Documents\Code\projects\SecurityRabbitTest\src\main.py", line 30, in process_files
    file_info = analysis.file_info(file_name)
  File "D:\Users\hank\Documents\Code\projects\SecurityRabbitTest\src\analysis.py", line 89, in file_info
    dll_import_analysis_dict = dll_import_analysis(pe_file)
  File "D:\Users\hank\Documents\Code\projects\SecurityRabbitTest\src\analysis.py", line 219, in dll_import_analysis
    return dll_analysis_dict
UnboundLocalError: local variable 'dll_analysis_dict' referenced before assignment


